// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIMPE.Dashboard.Data;

#nullable disable

namespace SIMPE.Dashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429035727_AddEquipos")]
    partial class AddEquipos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SIMPE.Dashboard.Models.Equipo", b =>
                {
                    b.Property<string>("id_equipo")
                        .HasColumnType("TEXT");

                    b.Property<string>("antivirus_nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cpu_model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("disco_tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("estado_seguridad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hardware_detalles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("os_version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ram_total")
                        .HasColumnType("REAL");

                    b.Property<int>("synced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tiempo_apagado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tiempo_arranque")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ultima_actualizacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id_equipo");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("SIMPE.Dashboard.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
